version: "3"
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./apache:/etc/apache2/sites-available
    ports:
      - "8080:80"
    networks:
      - laravel


networks:
  laravel:
